collection:
  batch_size: 50
  interval: 15s
  collectors:
    cpu:
      enabled: false
      interval: 10s
      include_temps: true
    memory:
      enabled: false
      interval: 15s
    disk:
      enabled: true
      interval: 30s
      ignore_paths: ["/tmp"]
